### ISSUE TITLE
Plugin is violating developer policies regarding telemetry

### ISSUE THREAD

**Issue by joethei** [zincplusplus/habit-tracker#36]
Hi @zincplusplus,

Since you posted about your analytics service on the forum I investigated your plugin and found that it violates our [Developer policies](https://docs.obsidian.md/Developer+policies)

Plugins should not submit user data to third-party telemetry services from within Obsidian, even if the data collection is opt-in.
Please remove the offending code within 30 days and create a new release, otherwise this plugin will be removed from the community plugins directory.

Thanks,
— The Obsidian team

**Comment by zincplusplus** [comment]
Ah shit. When I was first building my plugin I’m sure I read that we can add tracking, as long as it’s mentioned. Did that change or am I remembering it wrong?

**Comment by joethei** [comment]
Please see my forum reply.

**Comment by zincplusplus** [comment]
@joethei Ah shit. When I was first building my plugin I’m sure I read that we can add tracking, as long as it’s mentioned. Did that change or am I remembering it wrong?

**Comment by zincplusplus** [comment]
@joethei fixed with release https://github.com/zincplusplus/habit-tracker/releases/tag/1.4.3
