### ISSUE TITLE
BUG - After updating to the latest version, the markers are no longer displayed in the table

### ISSUE THREAD

**Issue by Ihopeyouarehappy** [zincplusplus/habit-tracker#39]
obsidian version :  1.6.7
habit tracker version : 1.4.3

After updating to the latest version, the markers are no longer displayed in the table.

![PixPin_2024-07-27_21-39-36](https://github.com/user-attachments/assets/ac54c419-e431-480e-a412-83bc0b9759ab)

**Comment by ganser8** [comment]
same here

**Comment by zincplusplus** [comment]
Can confirm. Looking into it now

**Comment by zincplusplus** [comment]
Fixed with 1.4.4 https://github.com/zincplusplus/habit-tracker/releases/tag/1.4.4

**Comment by zincplusplus** [comment]
Thanks so much guys for finding this and reporting 🙏

**Comment by Ihopeyouarehappy** [comment]
> Thanks so much guys for finding this and reporting 🙏

I like this plugin, it's very good! Thank you for fixed it.
